---
- name: SELinux para o modo disabled
  selinux:
    policy: targeted
    state: disabled

- name: Verificando se o firewalld esta ativo
  systemd:
    name: firewalld
  register: firewalld_status

- name: Liberando a porta {{ agent_ListenPort }}/tcp permanentemente no firewalld
  firewalld:
    port: "{{ agent_ListenPort }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  when: firewalld_status.status.ActiveState == 'active'

- name: Verificando se o arquivo epel.repo existe
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo_file

- name: Adicionando a linha excludepkgs ao arquivo epel.repo
  lineinfile:
    path: /etc/yum.repos.d/epel.repo
    line: excludepkgs=zabbix*
    insertafter: \[epel\]
  when: epel_repo_file.stat.exists == True

- name: Instalando repositório
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Instalando Zabbix Agent 2
  yum:
    name: ['zabbix-agent2', 'zabbix-agent2-plugin-*']
    state: present